group: spe
nodes: 1
cores: 10
walltime: '3:00:00'
mem: 120G
jobname: 'hgram_l={l}_k={k}_d={d}_{date}'
outputdir: ../hnn_tests
datadir: ../data

parameters:
  # frequencies to be used to make the holograms
  k: [0.0001]
  # maximum frequencies used in fourier transforms
  l: [6]
  # noise distances
  d: [5]

command: |
  source activate tensorflowenv
  python -u main_memory_bug.py {l} {k} {d} --config {config}
