group: spe
nodes: 1
cores: 4
walltime: '4:00:00'
mem: 20G
jobname: 'hgram_l={l}_k={k}_d={d}_{date}'
outputdir: ./output
datadir: ./data

parameters:
  # frequencies to be used to make the holograms
  k: [0.0001]
  # maximum frequencies used in fourier transforms
  l: [6]
  # noise distances
  d: [10.0]

command: |
  source activate tensorflowenv
  python -u network/train.py -L {l} -k {k} -d {d} --datadir {datadir} --outputdir {outputdir} --verbosity 2
