sbatch: |
  #!/bin/bash
  ## Job Name
  #SBATCH --job-name={jobname}
  ## Allocation Definition
  ## The account and partition options should be the same except in a few cases (e.g. ckpt queue and genpool queue).
  #SBATCH --account={group}
  #SBATCH --partition={partition}
  #SBATCH --gres=gpu:P100:1	
  ## Resources
  ## Total number of Nodes
  #SBATCH --nodes={nodes}
  ## Number of cores per node
  #SBATCH --ntasks-per-node={cores}
  ## Walltime (3 hours). Do not specify a walltime substantially more than your job needs.
  #SBATCH --time={walltime}
  ## Memory per node. It is important to specify the memory since the default memory is very small.
  ## For mox, --mem may be more than 100G depending on the memory of your nodes.
  ## For ikt, --mem may be 58G or more depending on the memory of your nodes.
  ## See above section on "Specifying memory" for choices for --mem.
  #SBATCH --mem={mem}
  ## Specify the working directory for this job
  #SBATCH --chdir={chdir}
  ##turn on e-mail notification
  #SBATCH --mail-type=ALL
  #SBATCH --mail-user={user}@uw.edu
  ## export all your environment variables to the batch job session
  #SBATCH --export=all
  #SBATCH -e {outputdir}/{jobname}.err
  #SBATCH -o {outputdir}/{jobname}.log


